# coding: utf-8
validColors = ("White", "Black", "Green", "Blue", "Red", "Yellow")
validShapes = ("Circle", "Square", "Triangle")

countries = {"Oceania": ("Sumatra", "Borneo", "Nova Guine", "Australia"),
			"America do Norte": ("Alaska", "Mackenzie", "Groenlandia",
								"Vancouver", "Ottawa", "Labrador", "California",
								"Nova York", "Mexico"),
			"America do Sul": ("Colombia", "Bolivia", "Brasil", "Argentina"),
			"Europa": ("Islandia", "Suecia", "Moscou", "Inglaterra",
						"Alemanha",	"Espanha", "Polonia"),
			"Africa": ("Argelia", "Egito", "Sudao", "Congo",
						"Africa do Sul", "Madagascar"),
			"Asia": ("Oriente Medio", "Aral", "Omsk", "Dudinka", "Siberia",
					"Tchita", "Vladivostok", "Mongolia", "Japao", "China",
					"India", "Vietna")}
				
territoryLinks = (("Brasil", "Argentina"),
				("Brasil", "Bolivia"),
				("Brasil", "Colombia"),
				("Brasil", "Argelia"),
				("Bolivia", "Colombia"),
				("Bolivia", "Argentina"),
				("Colombia", "Mexico"),
				("Mexico", "Nova York"),
				("Mexico", "California"),
				("Nova York", "California"),
				("California", "Vancouver"),
				("California", "Ottawa"),
				("Nova York", "Ottawa"),
				("Nova York", "Labrador"),
				("Ottawa", "Labrador"),
				("Vancouver", "Ottawa"),
				("Vancouver", "Alaska"),
				("Vancouver", "Mackenzie"),
				("Alaska", "Mackenzie"),
				("Ottawa", "Mackenzie"),
				("Labrador", "Groenlandia"),
				("Mackenzie", "Groenlandia"),
				("Groenlandia", "Islandia"),
				("Alaska", "Vladivostok"),
				("Islandia", "Inglaterra"),
				("Inglaterra", "Suecia"),
				("Inglaterra", "Alemanha"),
				("Inglaterra", "Espanha"),
				("Espanha", "Alemanha"),
				("Espanha", "Polonia"),
				("Polonia", "Alemanha"),
				("Polonia", "Moscou"),
				("Moscou", "Suecia"),
				("Moscou", "Omsk"),
				("Moscou", "Aral"),
				("Moscou", "Oriente Medio"),
				("Polonia", "Oriente Medio"),
				("Polonia", "Egito"),
				("Espanha", "Egito"),
				("Espanha", "Argelia"),
				("Argelia", "Egito"),
				("Argelia", "Sudao"),
				("Egito", "Sudao"),
				("Argelia", "Congo"),
				("Sudao", "Congo"),
				("Congo", "Africa do Sul"),
				("Africa do Sul", "Madagascar"),
				("Sudao", "Madagascar"),
				("Oriente Medio", "Egito"),
				("Oriente Medio", "Aral"),
				("Oriente Medio", "India"),
				("Aral", "India"),
				("Aral", "Omsk"),
				("Aral", "China"),
				("India", "China"),
				("India", "Vietna"),
				("Vietna", "China"),
				("China", "Omsk"),
				("China", "Mongolia"),
				("China", "Japao"),
				("Omsk", "Dudinka"),
				("Dudinka", "Mongolia"),
				("Mongolia", "Tchita"),
				("Dudinka", "Tchita"),
				("Dudinka", "Siberia"),
				("Siberia", "Tchita"),
				("Tchita", "Vladivostok"),
				("Siberia", "Vladivostok"),
				("China", "Vladivostok"),
				("Japao", "Vladivostok"),
				("India", "Sumatra"),
				("Vietna", "Borneo"),
				("Borneo", "Nova Guine"),
				("Borneo", "Australia"),
				("Australia", "Nova Guine"),
				("Australia", "Sumatra"))

debug = True
