# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='communication.proto',
  package='',
  serialized_pb='\n\x13\x63ommunication.proto\"#\n\x04\x43\x61rd\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05shape\x18\x02 \x02(\t\"\xa8\x04\n\x0e\x43lientToServer\x12/\n\x0bplayer_info\x18\x01 \x01(\x0b\x32\x1a.ClientToServer.PlayerInfo\x12-\n\ntrade_info\x18\x02 \x01(\x0b\x32\x19.ClientToServer.TradeInfo\x12\x35\n\x0ereinforce_info\x18\x03 \x03(\x0b\x32\x1d.ClientToServer.ReinforceInfo\x12/\n\x0b\x61ttack_info\x18\x04 \x01(\x0b\x32\x1a.ClientToServer.AttackInfo\x12\x33\n\rrelocate_info\x18\x05 \x01(\x0b\x32\x1c.ClientToServer.RelocateInfo\x12\x10\n\x08\x65nd_turn\x18\x06 \x01(\x08\x1a\x1b\n\nPlayerInfo\x12\r\n\x05\x63olor\x18\x01 \x02(\t\x1a!\n\tTradeInfo\x12\x14\n\x05\x63\x61rds\x18\x01 \x03(\x0b\x32\x05.Card\x1a\x30\n\rReinforceInfo\x12\x11\n\tterritory\x18\x01 \x02(\t\x12\x0c\n\x04size\x18\x02 \x02(\r\x1aR\n\nAttackInfo\x12\x0e\n\x06source\x18\x01 \x02(\t\x12\x13\n\x0b\x64\x65stination\x18\x02 \x02(\t\x12\x11\n\tarmy_size\x18\x03 \x02(\r\x12\x0c\n\x04move\x18\x04 \x02(\r\x1a\x41\n\x0cRelocateInfo\x12\x0e\n\x06source\x18\x01 \x02(\t\x12\x13\n\x0b\x64\x65stination\x18\x02 \x02(\t\x12\x0c\n\x04move\x18\x03 \x02(\r\"\xec\x02\n\x0eServerToClient\x12\x35\n\x0eterritory_info\x18\x01 \x03(\x0b\x32\x1d.ServerToClient.TerritoryInfo\x12\x31\n\x0c\x61ttack_reply\x18\x02 \x01(\x0b\x32\x1b.ServerToClient.AttackReply\x12+\n\tturn_info\x18\x03 \x01(\x0b\x32\x18.ServerToClient.TurnInfo\x12\x14\n\x05\x63\x61rds\x18\x04 \x03(\x0b\x32\x05.Card\x1a:\n\rTerritoryInfo\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05owner\x18\x02 \x02(\t\x12\x0c\n\x04size\x18\x03 \x02(\r\x1aG\n\x0b\x41ttackReply\x12\x0f\n\x07success\x18\x01 \x02(\x08\x12\x11\n\tred_dices\x18\x02 \x03(\r\x12\x14\n\x0cyellow_dices\x18\x03 \x03(\r\x1a(\n\x08TurnInfo\x12\x0e\n\x06player\x18\x01 \x02(\t\x12\x0c\n\x04step\x18\x02 \x02(\t')




_CARD = descriptor.Descriptor(
  name='Card',
  full_name='Card',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='Card.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='shape', full_name='Card.shape', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=23,
  serialized_end=58,
)


_CLIENTTOSERVER_PLAYERINFO = descriptor.Descriptor(
  name='PlayerInfo',
  full_name='ClientToServer.PlayerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='color', full_name='ClientToServer.PlayerInfo.color', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=350,
  serialized_end=377,
)

_CLIENTTOSERVER_TRADEINFO = descriptor.Descriptor(
  name='TradeInfo',
  full_name='ClientToServer.TradeInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='cards', full_name='ClientToServer.TradeInfo.cards', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=379,
  serialized_end=412,
)

_CLIENTTOSERVER_REINFORCEINFO = descriptor.Descriptor(
  name='ReinforceInfo',
  full_name='ClientToServer.ReinforceInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='territory', full_name='ClientToServer.ReinforceInfo.territory', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='size', full_name='ClientToServer.ReinforceInfo.size', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=414,
  serialized_end=462,
)

_CLIENTTOSERVER_ATTACKINFO = descriptor.Descriptor(
  name='AttackInfo',
  full_name='ClientToServer.AttackInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='source', full_name='ClientToServer.AttackInfo.source', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='destination', full_name='ClientToServer.AttackInfo.destination', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='army_size', full_name='ClientToServer.AttackInfo.army_size', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='move', full_name='ClientToServer.AttackInfo.move', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=464,
  serialized_end=546,
)

_CLIENTTOSERVER_RELOCATEINFO = descriptor.Descriptor(
  name='RelocateInfo',
  full_name='ClientToServer.RelocateInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='source', full_name='ClientToServer.RelocateInfo.source', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='destination', full_name='ClientToServer.RelocateInfo.destination', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='move', full_name='ClientToServer.RelocateInfo.move', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=548,
  serialized_end=613,
)

_CLIENTTOSERVER = descriptor.Descriptor(
  name='ClientToServer',
  full_name='ClientToServer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='player_info', full_name='ClientToServer.player_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='trade_info', full_name='ClientToServer.trade_info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='reinforce_info', full_name='ClientToServer.reinforce_info', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='attack_info', full_name='ClientToServer.attack_info', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='relocate_info', full_name='ClientToServer.relocate_info', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='end_turn', full_name='ClientToServer.end_turn', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_CLIENTTOSERVER_PLAYERINFO, _CLIENTTOSERVER_TRADEINFO, _CLIENTTOSERVER_REINFORCEINFO, _CLIENTTOSERVER_ATTACKINFO, _CLIENTTOSERVER_RELOCATEINFO, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=61,
  serialized_end=613,
)


_SERVERTOCLIENT_TERRITORYINFO = descriptor.Descriptor(
  name='TerritoryInfo',
  full_name='ServerToClient.TerritoryInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='ServerToClient.TerritoryInfo.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='owner', full_name='ServerToClient.TerritoryInfo.owner', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='size', full_name='ServerToClient.TerritoryInfo.size', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=807,
  serialized_end=865,
)

_SERVERTOCLIENT_ATTACKREPLY = descriptor.Descriptor(
  name='AttackReply',
  full_name='ServerToClient.AttackReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='success', full_name='ServerToClient.AttackReply.success', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='red_dices', full_name='ServerToClient.AttackReply.red_dices', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='yellow_dices', full_name='ServerToClient.AttackReply.yellow_dices', index=2,
      number=3, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=867,
  serialized_end=938,
)

_SERVERTOCLIENT_TURNINFO = descriptor.Descriptor(
  name='TurnInfo',
  full_name='ServerToClient.TurnInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='player', full_name='ServerToClient.TurnInfo.player', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='step', full_name='ServerToClient.TurnInfo.step', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=940,
  serialized_end=980,
)

_SERVERTOCLIENT = descriptor.Descriptor(
  name='ServerToClient',
  full_name='ServerToClient',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='territory_info', full_name='ServerToClient.territory_info', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='attack_reply', full_name='ServerToClient.attack_reply', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='turn_info', full_name='ServerToClient.turn_info', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cards', full_name='ServerToClient.cards', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_SERVERTOCLIENT_TERRITORYINFO, _SERVERTOCLIENT_ATTACKREPLY, _SERVERTOCLIENT_TURNINFO, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=616,
  serialized_end=980,
)


_CLIENTTOSERVER_PLAYERINFO.containing_type = _CLIENTTOSERVER;
_CLIENTTOSERVER_TRADEINFO.fields_by_name['cards'].message_type = _CARD
_CLIENTTOSERVER_TRADEINFO.containing_type = _CLIENTTOSERVER;
_CLIENTTOSERVER_REINFORCEINFO.containing_type = _CLIENTTOSERVER;
_CLIENTTOSERVER_ATTACKINFO.containing_type = _CLIENTTOSERVER;
_CLIENTTOSERVER_RELOCATEINFO.containing_type = _CLIENTTOSERVER;
_CLIENTTOSERVER.fields_by_name['player_info'].message_type = _CLIENTTOSERVER_PLAYERINFO
_CLIENTTOSERVER.fields_by_name['trade_info'].message_type = _CLIENTTOSERVER_TRADEINFO
_CLIENTTOSERVER.fields_by_name['reinforce_info'].message_type = _CLIENTTOSERVER_REINFORCEINFO
_CLIENTTOSERVER.fields_by_name['attack_info'].message_type = _CLIENTTOSERVER_ATTACKINFO
_CLIENTTOSERVER.fields_by_name['relocate_info'].message_type = _CLIENTTOSERVER_RELOCATEINFO
_SERVERTOCLIENT_TERRITORYINFO.containing_type = _SERVERTOCLIENT;
_SERVERTOCLIENT_ATTACKREPLY.containing_type = _SERVERTOCLIENT;
_SERVERTOCLIENT_TURNINFO.containing_type = _SERVERTOCLIENT;
_SERVERTOCLIENT.fields_by_name['territory_info'].message_type = _SERVERTOCLIENT_TERRITORYINFO
_SERVERTOCLIENT.fields_by_name['attack_reply'].message_type = _SERVERTOCLIENT_ATTACKREPLY
_SERVERTOCLIENT.fields_by_name['turn_info'].message_type = _SERVERTOCLIENT_TURNINFO
_SERVERTOCLIENT.fields_by_name['cards'].message_type = _CARD

class Card(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CARD
  
  # @@protoc_insertion_point(class_scope:Card)

class ClientToServer(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class PlayerInfo(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _CLIENTTOSERVER_PLAYERINFO
    
    # @@protoc_insertion_point(class_scope:ClientToServer.PlayerInfo)
  
  class TradeInfo(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _CLIENTTOSERVER_TRADEINFO
    
    # @@protoc_insertion_point(class_scope:ClientToServer.TradeInfo)
  
  class ReinforceInfo(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _CLIENTTOSERVER_REINFORCEINFO
    
    # @@protoc_insertion_point(class_scope:ClientToServer.ReinforceInfo)
  
  class AttackInfo(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _CLIENTTOSERVER_ATTACKINFO
    
    # @@protoc_insertion_point(class_scope:ClientToServer.AttackInfo)
  
  class RelocateInfo(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _CLIENTTOSERVER_RELOCATEINFO
    
    # @@protoc_insertion_point(class_scope:ClientToServer.RelocateInfo)
  DESCRIPTOR = _CLIENTTOSERVER
  
  # @@protoc_insertion_point(class_scope:ClientToServer)

class ServerToClient(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class TerritoryInfo(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _SERVERTOCLIENT_TERRITORYINFO
    
    # @@protoc_insertion_point(class_scope:ServerToClient.TerritoryInfo)
  
  class AttackReply(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _SERVERTOCLIENT_ATTACKREPLY
    
    # @@protoc_insertion_point(class_scope:ServerToClient.AttackReply)
  
  class TurnInfo(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _SERVERTOCLIENT_TURNINFO
    
    # @@protoc_insertion_point(class_scope:ServerToClient.TurnInfo)
  DESCRIPTOR = _SERVERTOCLIENT
  
  # @@protoc_insertion_point(class_scope:ServerToClient)

# @@protoc_insertion_point(module_scope)
